// export const PLANS_VIEWS = {
// 	PLANS_LIST: 'PLANS_LIST',
// 	PLANS_ACTIONS: 'PLANS_ACTION',
// 	PLANS_DETAILS: 'PLANS_DETAILS',

// 	SUBS_LIST: 'SUBS_LIST',
// 	SUBS_ACTIONS: 'SUBS_ACTIONS',
// 	SUBS_DETAILS: 'SUBS_DETAILS',

// 	NEXT_LIST: 'NEXT_LIST'
// };
